version: '3'

services:

  ubuntu:
    image: ssh_on_docker:latest
    container_name: ubuntu
    restart: unless-stopped
    tty: true
    volumes:
      - ./assets:/assets
      - ./keys:/keys
    ports:
      - "8000:8000"
